package main

import (
	"bytes"
	_ "embed"
	"encoding/base64"
	"encoding/gob"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	goruntime "runtime"
	"strings"
	"text/template"

	"github.com/pranavms13/flux-lang/compiler"
	"github.com/pranavms13/flux-lang/config"
	"github.com/pranavms13/flux-lang/diagnostic"
	"github.com/pranavms13/flux-lang/parser"
	"github.com/pranavms13/flux-lang/runtime"
	"github.com/pranavms13/flux-lang/source"
	"github.com/pranavms13/flux-lang/types"
	"github.com/pranavms13/flux-lang/vm"
)

// Version information is set by build flags.
var (
	Version = "dev"
	Commit  = "unknown"
	Date    = "unknown"
)

// Embedding the VM makes compilation independent of the Flux source checkout.
//
//go:embed vm/vm.go
var vmSource string

func init() { gob.RegisterName("flux.Chunk", &vm.Chunk{}) }

const executableTemplate = `package main

import (
 "bytes"
 "encoding/base64"
 "encoding/gob"
 "fmt"
 "os"
)

func init() { gob.RegisterName("flux.Chunk", &Chunk{}) }

func main() {
 defer func() {
  if err := recover(); err != nil { fmt.Fprintln(os.Stderr, "Runtime error:", err); os.Exit(1) }
 }()
 bytecode, err := base64.StdEncoding.DecodeString("{{.Bytecode}}")
 if err != nil { panic(err) }
 var chunk Chunk
 if err := gob.NewDecoder(bytes.NewReader(bytecode)).Decode(&chunk); err != nil { panic(err) }
 New(&chunk).Run()
}
`

func main() {
	if err := runCLI(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		os.Exit(1)
	}
}

func runCLI(args []string) (err error) {
	// Runtime errors are reported as diagnostics instead of Go stack traces.
	defer func() {
		if failure := recover(); failure != nil {
			err = fmt.Errorf("%v", failure)
		}
	}()
	if len(args) == 0 {
		printUsage()
		return nil
	}
	switch args[0] {
	case "help", "--help", "-h":
		printUsage()
		return nil
	case "version", "--version":
		fmt.Printf("Flux Language v%s\nCommit: %s\nBuild Date: %s\n", strings.TrimPrefix(Version, "v"), Commit, Date)
		return nil
	case "init":
		if len(args) != 1 {
			return fmt.Errorf("usage: flux init")
		}
		if err := initializeProject(); err != nil {
			return err
		}
		fmt.Println("Initialized new Flux project with flux.json configuration file")
		return nil
	case "run", "compile":
		if len(args) != 2 {
			return fmt.Errorf("%s command requires one file argument", args[0])
		}
	default:
		return fmt.Errorf("unknown command %q; use flux help", args[0])
	}
	cfg, err := config.GetConfigFromCurrentDir()
	if err != nil {
		return err
	}
	text, err := os.ReadFile(args[1])
	if err != nil {
		return diagnostic.Tool("read source file", args[1], err)
	}
	parsed := parser.ParseSource(source.NewMap().Add(args[1], string(text)))
	if parsed.Failed() {
		return errors.New(formatDiagnostics(parsed.Source, parsed.Diagnostics))
	}
	prog := parsed.Program
	tc := types.NewTypeCheckerForSource(parsed.Source, types.TypeCheckingMode{
		Strict: cfg.TypeChecking.Strict, WarnOnly: cfg.TypeChecking.WarnOnly, Enabled: cfg.TypeChecking.Enabled,
	})
	tc.CheckProgram(prog)
	if tc.HasWarnings() {
		fmt.Fprintln(os.Stderr, "Type checking warnings:")
		for _, warning := range tc.GetWarnings() {
			fmt.Fprintf(os.Stderr, "  - %s\n", warning)
		}
	}
	if tc.HasErrors() {
		return fmt.Errorf("type checking failed:\n  - %s", strings.Join(tc.GetErrors(), "\n  - "))
	}
	if args[0] == "run" {
		runtime.Run(prog)
		return nil
	}
	output, err := compileExecutable(compiler.NewFluxCompiler().Compile(prog), args[1])
	if err != nil {
		return err
	}
	fmt.Printf("Compiled executable created at %s\n", output)
	return nil
}

func compileExecutable(chunk *vm.Chunk, sourcePath string) (string, error) {
	var bytecode bytes.Buffer
	if err := gob.NewEncoder(&bytecode).Encode(chunk); err != nil {
		return "", err
	}
	tempDir, err := os.MkdirTemp("", "flux-build-*")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(tempDir)
	tmpl, err := template.New("executable").Parse(executableTemplate)
	if err != nil {
		return "", err
	}
	var generated bytes.Buffer
	if err := tmpl.Execute(&generated, map[string]string{"Bytecode": base64.StdEncoding.EncodeToString(bytecode.Bytes())}); err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(tempDir, "main.go"), generated.Bytes(), 0600); err != nil {
		return "", err
	}
	standaloneVM := strings.Replace(vmSource, "package vm", "package main", 1)
	if err := os.WriteFile(filepath.Join(tempDir, "vm.go"), []byte(standaloneVM), 0600); err != nil {
		return "", err
	}
	if err := os.MkdirAll("dist", 0755); err != nil {
		return "", err
	}
	name := strings.TrimSuffix(filepath.Base(sourcePath), filepath.Ext(sourcePath))
	if goruntime.GOOS == "windows" {
		name += ".exe"
	}
	output := filepath.Join("dist", name)
	absoluteOutput, err := filepath.Abs(output)
	if err != nil {
		return "", err
	}
	cmd := exec.Command("go", "build", "-o", absoluteOutput, "main.go", "vm.go")
	cmd.Dir = tempDir
	if result, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("build executable (Go must be installed): %w\n%s", err, result)
	}
	return output, nil
}

// formatDiagnostics renders diagnostics as one line each, with their notes.
// It is a stopgap: P1.6 adds the real renderer, with source snippets, related
// locations, optional colour, and a JSON representation, and the checker and
// both engines report through it too.
func formatDiagnostics(src *source.Source, diagnostics []diagnostic.Diagnostic) string {
	rendered := make([]string, 0, len(diagnostics))
	for _, d := range diagnostics {
		position := src.Position(d.Primary.Start)
		line := fmt.Sprintf("%s:%d:%d: %s[%s]: %s",
			src.Name(), position.Line, position.Display, d.Severity, d.Code, d.Message)
		for _, note := range d.Notes {
			line += "\n  = note: " + note
		}
		rendered = append(rendered, line)
	}
	return strings.Join(rendered, "\n")
}

func printUsage() {
	fmt.Println("Usage: flux <command> [file.flux]")
	fmt.Println("Commands:")
	fmt.Println("\tversion - Show version information")
	fmt.Println("\tcompile <file.flux> - Compile to a standalone executable (requires Go)")
	fmt.Println("\trun <file.flux> - Run a Flux source file")
	fmt.Println("\tinit - Create a flux.json configuration file")
}

func initializeProject() error {
	f, err := os.OpenFile("flux.json", os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0644)
	if err != nil {
		return fmt.Errorf("initialize project: %w", err)
	}
	encoder := json.NewEncoder(f)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(config.DefaultConfig()); err != nil {
		f.Close()
		return err
	}
	return f.Close()
}
